plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xcluice.digitalwellbeing'
    compileSdk 34

    defaultConfig {
        applicationId 'com.xcluice.digitalwellbeing'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile file('release.jks')
            storePassword 'geminishell'
            keyAlias 'key'
            keyPassword 'geminishell'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
